### ISSUE TITLE
Details of Training

### ISSUE THREAD

**Issue by aakashchoubey** [YongWookHa/pose2pose#1]
I'd like to ask a few questions about the training of the model.

1. Which video did you take as source and which as target? From my understanding, your own video would be source and Bruno Mars video as target, is that correct?
2. How many images did you have in your original (or landmarks) folder for both source and target videos?
3. What kind of hardware did you use to train the model?
4. How much time did it take to train and test the model on this hardware?
5. What more do you think we can do to improve the results?

Thanks.

**Comment by YongWookHa** [comment]
Hello, 
Here's the reply.

1. Yes. You are correct. The model learns how to draw my body from skeleton image. After learning, you will give the model the dancing skeleton image of Bruno Mars. then It will paint your body over Bruno Mars's dancing skeleton. 
2. Actually, I didn't use many images. As i remember, I used around 1 min video which is 30fps. That's why I set the epoch `1000`.
3. I used nvidia GTX 1080 with 8GB video RAM.
4. I remember it took around 10hr for learning. I'd say I'm not really sure.
5. I didn't try it after all, but I think for better result, we can use some kind of [auxilirary classifier](https://arxiv.org/pdf/1610.09585.pdf) which contain the ordinate information of skeletons. (openpose provides them!). Of course, you will get much better result if you record better video of your own. _better video would contain various pose frames excluding duplications._

I hope this reply to be helpful.
Have a nice day.
